/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  IsDate,
  ValidateNested,
} from "class-validator";
import { Type } from "class-transformer";
import { PackageModelWhereUniqueInput } from "../../packageModel/base/PackageModelWhereUniqueInput";
import { PracticeCreateNestedManyWithoutLessonsInput } from "./PracticeCreateNestedManyWithoutLessonsInput";
import { TestCreateNestedManyWithoutLessonsInput } from "./TestCreateNestedManyWithoutLessonsInput";
import { TextMaterialCreateNestedManyWithoutLessonsInput } from "./TextMaterialCreateNestedManyWithoutLessonsInput";
import { VideoCreateNestedManyWithoutLessonsInput } from "./VideoCreateNestedManyWithoutLessonsInput";

@InputType()
class LessonCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  content?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  deletedAt?: Date | null;

  @ApiProperty({
    required: false,
    type: () => PackageModelWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PackageModelWhereUniqueInput)
  @IsOptional()
  @Field(() => PackageModelWhereUniqueInput, {
    nullable: true,
  })
  packageField?: PackageModelWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => PracticeCreateNestedManyWithoutLessonsInput,
  })
  @ValidateNested()
  @Type(() => PracticeCreateNestedManyWithoutLessonsInput)
  @IsOptional()
  @Field(() => PracticeCreateNestedManyWithoutLessonsInput, {
    nullable: true,
  })
  practices?: PracticeCreateNestedManyWithoutLessonsInput;

  @ApiProperty({
    required: false,
    type: () => TestCreateNestedManyWithoutLessonsInput,
  })
  @ValidateNested()
  @Type(() => TestCreateNestedManyWithoutLessonsInput)
  @IsOptional()
  @Field(() => TestCreateNestedManyWithoutLessonsInput, {
    nullable: true,
  })
  tests?: TestCreateNestedManyWithoutLessonsInput;

  @ApiProperty({
    required: false,
    type: () => TextMaterialCreateNestedManyWithoutLessonsInput,
  })
  @ValidateNested()
  @Type(() => TextMaterialCreateNestedManyWithoutLessonsInput)
  @IsOptional()
  @Field(() => TextMaterialCreateNestedManyWithoutLessonsInput, {
    nullable: true,
  })
  textMaterials?: TextMaterialCreateNestedManyWithoutLessonsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;

  @ApiProperty({
    required: false,
    type: () => VideoCreateNestedManyWithoutLessonsInput,
  })
  @ValidateNested()
  @Type(() => VideoCreateNestedManyWithoutLessonsInput)
  @IsOptional()
  @Field(() => VideoCreateNestedManyWithoutLessonsInput, {
    nullable: true,
  })
  videos?: VideoCreateNestedManyWithoutLessonsInput;
}

export { LessonCreateInput as LessonCreateInput };
