/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { StringFilter } from "../../util/StringFilter";
import { PackageModelWhereUniqueInput } from "../../packageModel/base/PackageModelWhereUniqueInput";
import { PracticeListRelationFilter } from "../../practice/base/PracticeListRelationFilter";
import { TestListRelationFilter } from "../../test/base/TestListRelationFilter";
import { TextMaterialListRelationFilter } from "../../textMaterial/base/TextMaterialListRelationFilter";
import { VideoListRelationFilter } from "../../video/base/VideoListRelationFilter";

@InputType()
class LessonWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  content?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => PackageModelWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PackageModelWhereUniqueInput)
  @IsOptional()
  @Field(() => PackageModelWhereUniqueInput, {
    nullable: true,
  })
  packageField?: PackageModelWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => PracticeListRelationFilter,
  })
  @ValidateNested()
  @Type(() => PracticeListRelationFilter)
  @IsOptional()
  @Field(() => PracticeListRelationFilter, {
    nullable: true,
  })
  practices?: PracticeListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => TestListRelationFilter,
  })
  @ValidateNested()
  @Type(() => TestListRelationFilter)
  @IsOptional()
  @Field(() => TestListRelationFilter, {
    nullable: true,
  })
  tests?: TestListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => TextMaterialListRelationFilter,
  })
  @ValidateNested()
  @Type(() => TextMaterialListRelationFilter)
  @IsOptional()
  @Field(() => TextMaterialListRelationFilter, {
    nullable: true,
  })
  textMaterials?: TextMaterialListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  title?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => VideoListRelationFilter,
  })
  @ValidateNested()
  @Type(() => VideoListRelationFilter)
  @IsOptional()
  @Field(() => VideoListRelationFilter, {
    nullable: true,
  })
  videos?: VideoListRelationFilter;
}

export { LessonWhereInput as LessonWhereInput };
