/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  IsDate,
  ValidateNested,
} from "class-validator";
import { Type } from "class-transformer";
import { PackageModel } from "../../packageModel/base/PackageModel";
import { Practice } from "../../practice/base/Practice";
import { Test } from "../../test/base/Test";
import { TextMaterial } from "../../textMaterial/base/TextMaterial";
import { Video } from "../../video/base/Video";

@ObjectType()
class Lesson {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  content!: string | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  deletedAt!: Date | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: () => PackageModel,
  })
  @ValidateNested()
  @Type(() => PackageModel)
  @IsOptional()
  packageField?: PackageModel | null;

  @ApiProperty({
    required: false,
    type: () => [Practice],
  })
  @ValidateNested()
  @Type(() => Practice)
  @IsOptional()
  practices?: Array<Practice>;

  @ApiProperty({
    required: false,
    type: () => [Test],
  })
  @ValidateNested()
  @Type(() => Test)
  @IsOptional()
  tests?: Array<Test>;

  @ApiProperty({
    required: false,
    type: () => [TextMaterial],
  })
  @ValidateNested()
  @Type(() => TextMaterial)
  @IsOptional()
  textMaterials?: Array<TextMaterial>;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title!: string | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;

  @ApiProperty({
    required: false,
    type: () => [Video],
  })
  @ValidateNested()
  @Type(() => Video)
  @IsOptional()
  videos?: Array<Video>;
}

export { Lesson as Lesson };
