/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AnswerCreateNestedManyWithoutUsersInput } from "./AnswerCreateNestedManyWithoutUsersInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { EnumUserRole } from "./EnumUserRole";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { UserPackageCreateNestedManyWithoutUsersInput } from "./UserPackageCreateNestedManyWithoutUsersInput";
import { UserPracticeResponseCreateNestedManyWithoutUsersInput } from "./UserPracticeResponseCreateNestedManyWithoutUsersInput";

@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: () => AnswerCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => AnswerCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => AnswerCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  answers?: AnswerCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: false,
    enum: EnumUserRole,
  })
  @IsEnum(EnumUserRole)
  @IsOptional()
  @Field(() => EnumUserRole, {
    nullable: true,
  })
  role?: "Option1" | null;

  @ApiProperty({
    required: true,
  })
  @IsJSONValue()
  @Field(() => GraphQLJSON)
  roles!: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => UserPackageCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => UserPackageCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => UserPackageCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  userPackages?: UserPackageCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => UserPracticeResponseCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => UserPracticeResponseCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => UserPracticeResponseCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  userPracticeResponses?: UserPracticeResponseCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;
}

export { UserCreateInput as UserCreateInput };
